name: electrops
description: Eshop.


publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  email_validator: ^2.1.17
  cloud_firestore: ^3.4.3

  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/

 
  uses-material-design: true

  
